# The Problem
In statistics, Bayesian analysis (BA), has the tremendous advantage of combining existing and relevant information with the data at hand by the incorporation of priors in the estimation process. BA answers research questions using probability statements, which are naturally framed because of the underlying assumption that all parameters are random quantities. This allows to summarize a parameter by an entire distribution of values – i.e. the posterior – instead of one fixed value as in frequentist analysis.
A posterior distribution comprises of a prior distribution about a parameter and a likelihood model providing information about the parameter based on the observed data. Depending on the chosen prior, distribution and likelihood model, the posterior distribution is either available analytically or approximated by, for example, one of the Markov chain Monte Carlo (MCMC) methods. 
BA has several appealing features, including the ability to make inference on complex data structures, provide a comprehensive view of parameter uncertainty. In fact, posterior distributions provide us with point estimates such as posterior means, medians, percentiles, and interval estimates known as credible (or probability) intervals. All statistical tests about model parameters can be expressed as probability statements based on the estimated posterior distribution.
BA is expanding and becoming endemic in a wide range of fields. However, an even more wide spreading is hampered by the challenge in providing reasonable priors. This is often a daunting task because the experts that provide prior information do not have a very good knowledge of the mathematics behind the scene.
As pointed out by Gelman, Simpson and Betancourt (2017 arxiv.org/abs/1708.07487) much of the recent progresses in BA points toward the beneﬁts of including real, subject-matter-speciﬁc, prior information to get more stable and accurate inferences. This puts new and signiﬁcant burdens on the developers and users of Bayesian methods, and an obligation for statisticians to develop default priors, or more generally procedures for researchers to build bespoke priors, going beyond the traditional recommendations. At the same time, those researchers need to recognize the importance of the prior and spend the time encoding their expertise in probabilistic form.
This process is not straightforward and could sensibly change the inferences.
It would be ideal to provide a tool that can be used to generate prior distributions to be used in BA for most of the available and commonly used statistical models under a package that will only require prior input from simple distributions or summary of experts’ opinion elicitation. It would be even better if that prior generating process could start from a web-based application in which the experts can interactively play with tables, histograms or densities to express their prior beliefs.
PriorGen is an R package that was built to translate beliefs into prior information in the form of Beta and Gamma distributions that can be mainly used for the generation of priors for estimation of disease prevalence and the sensitivity/specificity of diagnostic tests. We propose to rebuild PriorGen and make it a place-to-go for generating priors for most of the models that are used in BA. We intend to expand PriorGen and make it (i) a general purpose tool for translating prior beliefs in the form of statistical distributions and (ii) the engine of a Shiny App for a user-friendly experience. The new version of PriorGen will facilitate prior specification for most of the existing statistical models without requiring from the experts to have advanced mathematical skills. In this way, relevant expert opinion will be concisely incorporated in BA models. The new PriorGen will also add value to existing and extremely popular R-packages for BA like the rjags and rstan package and is expected to further facilitate and popularize the use of the corresponding invaluable tools for BA.


