# The proposal

## Overview

Our proposal is to fundamentally rebuild and redesign the PriorGen package, taking into account additional prior distributions that are commonly used in other contexts and building a Shiny interface within the package itself. This will help PriorGen evolve into a single and broadly-applicable tool for translating prior beliefs in the form of statistical distributions. The new version of PriorGen will facilitate prior specification for most of the existing statistical models without requiring advanced mathematical skills from relevant experts. This will facilitate the incorporation of relevant expert opinion within a wide range of BA models, and will make PriorGen a general-purpose tool for translating prior beliefs in the form of statistical distributions in a user-friendly way.


## Detail

The minimum viable product is an R package that provides a set of R functions to generate prior distributions from probability statements generated by the users.  This will initially cover the normal, gamma and beta distributions when used as priors for location parameters, (inverse) variability parameters, and prevalence parameters, respectively, both within standard generalised linear mixed models as well as a number of more specialist applications such as latent class models for the evaluation of diagnostic tests.  The provision of a fully-functional Shiny interface as an alternative method of generating all prior distributions contained in the package is essential.

The architecture will be kept simple, with an intensive use of the rootSolve package.  The majority of the coding time will be spent on designing and refining the Shiny interface, and ensuring that it caters to the needs of R users with a wide range of experience with Bayesian statsitical methods.  The revised R package will be hosted on a public GitHub repository created within the Section for Animal Welfare and Disease Control (University of Copenhagen) organisational repository (http://github.com/ku-awdc), and the Shiny application will be embedded (and easily runnable) within the R package itself as well as publically hosted via the same organisational account at http://shinyapps.io  We therefore hope to reach as wide a user base as possible, and will welcome active participation from the wider community.

The final version of PriorGen package will be released on CRAN, and subsequent updates to the runjags package will reference and make use of the additional facilities provided by the new PriorGen package.

