# Project team

* Matthew Denwood is Associate Professor in Quantitative Veterinary Epidemiology and Biostatistics at the Department of Veterinary and Animal Sciences, University of Copenhagen. His main research interests are in the application of computationally intensive statistical techniques to complex biological problems, particularly using techniques such as Markov chain Monte Carlo (MCMC). He is author and maintainer of the CRAN package runjags, which facilitates using Just Another Gibbs Sampler (JAGS) within R, and has also contributed directly to JAGS as well as the rjags package.  He has around 15 years experience of programming with R, and 25 years experience with HTML and Javascript that he has more recently put to good use writing Shiny apps.

* Paolo Eusebi is a Consultant Statistician and Statistical Programmer. He is working as Contract Statistician for UCB and as Consultant Statistician for Regional Helath Authority of Umbria. He is also adjunct Professor of Medical Statistics at the Epidemiology Department of Perugia University. His main research interests are the application of mixture models in meta-analysis, the use of machine learning techniques for subgroup identification and the display of uncertainty in scientific communication. He is Associate Editor of BMC Medical Research Methodology.

* Polychronis Kostoulas is Assistant Professor in Veterinary Epidemiology at the Faculty of Veterinary Medicine of the University of Thessaly. His research interests are in quantitative epidemiology, mostly focused on the application of Bayesian latent class models in diagnostic test evaluation, risk factor studies, risk assessment, quantification of disease heterogeneity and survival analysis. He is Co-Editor-in-Chief of Preventive Veterinary Medicine and administrator of the LCMATE mailing list community concerning Latent Class Models for the Accuracy of Tests.  He is also the lead coordinator of a recently-funded COST action CA18208 "Novel tools for test evaluation and disease prevalence estimation", and the current maintainer of the CRAN package PriorGen.
