# Project plan

The project will run from Jan 1st, 2020 to Dec 31, 2020.

## Phase 1:  Start-up

The following specific tasks will be accomplished as part of the start-up phase within the first 3-6 months of the project:

* Initial tasks
  + Approval of code of conduct
  + Gather formal expressions of interest via LCMATE mailing list community and professional networks
  + Set up GitHub page for development of R package (to be licensed under the GNU General Public License)
  + Writing of Shiny app templates for demonstration purposes

* Planning and Workshops
  + Hold teleconference meetings and small workshops (in conjunction with COST action "Novel tools for test evaluation and disease prevalence estimation")
  + Establish a list of desired package functions (input objects and parameters, output)
  + Establish a list of desired features for the Shiny interface
  + Map all the potential options for prior beliefs in terms of data (e.g. nominal, ordinal, count, continuous) and input (expert panel, parameters, histograms)

We will ensure that a quarterly update of our project will be shared on the R Consortium blog.

## Phase 2:  Code Delivery

This phase will form the bulk of the project, where the R code, Shiny app, and documentation and vignettes within the R package will be developed to meet the objectives identified in phase 1 and subsequently refined in response to feedback obtained from our community of users.  These activities will take place continually over the lifetime of the project.  

## Phase 3:  Dissemination

This phase will see the final R package released to CRAN, and the Shiny app to http://shinyapps.io  

Once the PriorGen package is complete, then reference to these facilities will be added to the runjags package.

## Other aspects

We plan to disseminate our work by conference presentation, and also by writing a peer-reviewed article outlining the PriorGen package (to be submitted to an open-access journal such as The R Journal / BMC Med Research Methodology / PlosOne).  We also plan to develop our existing community by building around this project using:

* three seminars at Copenaghen, Perugia and Tessaly
* dissemination activities during the COST action "Novel tools for test evaluation and disease prevalence estimation".
* presentation of the idea at the PSI Conference
* poster presentation at the Society for Veterinary Epidemiology and Preventive Medicine conference
* implementation of the R package at UCB Validated R (environment for use of R in the UCB company)
* presentation at UseR! Conference
